// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoringBot.Infrastructure.Persistence.DatabaseContexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonitoringBot.Infrastructure.Migrations
{
    [DbContext(typeof(MonitoringBotDbContextBase))]
    [Migration("20250706133000_Snapshots_TimeStamp")]
    partial class Snapshots_TimeStamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MonitoringBot.Infrastructure.Persistence.Entities.BotUserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsForum")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("BotUsers");
                });

            modelBuilder.Entity("MonitoringBot.Infrastructure.Persistence.Entities.ChannelMemberEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChannelReference")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<string>("LastAction")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("LastAction");

                    b.HasIndex("TimeStamp");

                    b.ToTable("ChannelMembers");
                });

            modelBuilder.Entity("MonitoringBot.Infrastructure.Persistence.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateNameProjection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CurrentTimeSequenceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityIdProjection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityNameProjection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TimeStamp", "CurrentTimeSequenceNumber");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("MonitoringBot.Infrastructure.Persistence.Entities.Snapshots.AggregateSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LastEventSequenceNumberForTimeStamp")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastEventTimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastProcessedEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("TotalEntities")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LastEventTimeStamp");

                    b.ToTable("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
